body:
  - type: markdown
    attributes:
      value: |
        Form I'm human at below.

  - type: textarea
    id: detail-diskusi
    attributes:
      label: Discuss
      description: "Type want to discuss."
      placeholder: "Type here ..."
    validations:
      required: true

  - type: dropdown
    id: human
    attributes:
      label: Are you human?
      options:
      - "Iya"
      - "はい"
      - "Yes"
    validations:
      required: true

  - type: checkboxes
    id: konfirmasi
    attributes:
      label: Konfirmasi dulu ya
      options:
        - label: "Gua udah check LICENSE and CODE OF CONDUCT"
          required: true
        - label: "Gua janji gua manusia"
          required: true
        - label: "Gua pake Vanilla JS (opsional)"
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        *Terima Kasih | Thank You | ありがとう。*
