name: Tanya Kido
label: Tanya apa?
body:
  - type: dropdown
    id: tech
    attributes:
      label: Lu pake Vanilla JS?
      options:
        - "はい"
        - "Yes"
        - Ya
    validations:
      required: true
