name: "General"
description: "Ask Kido"
title: "[Tanya] "
body:
  - type: dropdown
    id: tech
    attributes:
      label: "Lu pake Vanilla JS?"
      options:
        - Iya
        - Yes
    validations:
      required: true
